@startuml

allowmixing

!define SERVICE class
!define DATABASE database
!define QUEUE queue

package "Loyaltea - Loyalty Program SaaS" {
    SERVICE Fulfillment <<Python>>
    SERVICE Reward <<Python>>
    SERVICE Campaign <<Scala>>
    SERVICE User <<Scala>>
    DATABASE PostgreSQL
    QUEUE Kafka

    Fulfillment --> Kafka : Produce fulfillment events
    Kafka --> Campaign : Consume Fulfillment events
    Kafka <- Campaign : Produce Reward events
    Kafka --> Reward : Consume Reward events
    PostgreSQL <-up-> Fulfillment
    PostgreSQL <-left-> Campaign
    PostgreSQL <-down-> Reward
    PostgreSQL <-right-> User
}

@enduml
