# Generated by Django 5.0 on 2023-12-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fulfillment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('tenant', models.CharField()),
                ('campaign', models.UUIDField()),
                ('type', models.CharField(choices=[('wager', 'Wager'), ('tag', 'Tag')])),
            ],
        ),
    ]
