# Generated by Django 5.0 on 2023-12-20 15:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuyFulfillment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant', models.CharField()),
                ('fulfillment_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField()),
                ('product', models.CharField(blank=True)),
                ('amount', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TagFulfillment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant', models.CharField()),
                ('fulfillment_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField()),
                ('tag', models.CharField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
